[package]
name = "pf-enrichment"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Placeholder for pf-enrichment"

[dependencies]
