[package]
name = "pf-file-processor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Placeholder for pf-file-processor"

[dependencies]
