[package]
name = "pf-reader-parquet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Placeholder for pf-reader-parquet"

[dependencies]
