[package]
name = "pf-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "CLI for Paraflow Extreme"

[[bin]]
name = "pf-extreme"
path = "src/main.rs"

[dependencies]
