[package]
name = "pf-arrow-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Placeholder for pf-arrow-utils"

[dependencies]
