[package]
name = "pf-indexer-stdout"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Placeholder for pf-indexer-stdout"

[dependencies]
