[package]
name = "pf-queue-memory"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Placeholder for pf-queue-memory"

[dependencies]
